/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikisIndexRouteImport } from './routes/wikis/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryStoryKeyRouteImport } from './routes/library/$storyKey'
import { Route as BuilderStoriesRouteImport } from './routes/builder/stories'
import { Route as BuilderStoryKeyRouteImport } from './routes/builder/$storyKey'
import { Route as WikisWikiKeyIndexRouteImport } from './routes/wikis/$wikiKey/index'
import { Route as WikisWikiKeyNewRouteImport } from './routes/wikis/$wikiKey/new'
import { Route as GameGameKeySceneKeyRouteImport } from './routes/game/$gameKey/$sceneKey'
import { Route as WikisWikiKeyArticleKeyIndexRouteImport } from './routes/wikis/$wikiKey/$articleKey/index'
import { Route as WikisWikiKeyArticleKeyEditRouteImport } from './routes/wikis/$wikiKey/$articleKey/edit'
import { Route as GameTestGameKeySceneKeyRouteImport } from './routes/game/test/$gameKey/$sceneKey'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikisIndexRoute = WikisIndexRouteImport.update({
  id: '/wikis/',
  path: '/wikis/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryStoryKeyRoute = LibraryStoryKeyRouteImport.update({
  id: '/library/$storyKey',
  path: '/library/$storyKey',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderStoriesRoute = BuilderStoriesRouteImport.update({
  id: '/builder/stories',
  path: '/builder/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderStoryKeyRoute = BuilderStoryKeyRouteImport.update({
  id: '/builder/$storyKey',
  path: '/builder/$storyKey',
  getParentRoute: () => rootRouteImport,
} as any)
const WikisWikiKeyIndexRoute = WikisWikiKeyIndexRouteImport.update({
  id: '/wikis/$wikiKey/',
  path: '/wikis/$wikiKey/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikisWikiKeyNewRoute = WikisWikiKeyNewRouteImport.update({
  id: '/wikis/$wikiKey/new',
  path: '/wikis/$wikiKey/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameKeySceneKeyRoute = GameGameKeySceneKeyRouteImport.update({
  id: '/game/$gameKey/$sceneKey',
  path: '/game/$gameKey/$sceneKey',
  getParentRoute: () => rootRouteImport,
} as any)
const WikisWikiKeyArticleKeyIndexRoute =
  WikisWikiKeyArticleKeyIndexRouteImport.update({
    id: '/wikis/$wikiKey/$articleKey/',
    path: '/wikis/$wikiKey/$articleKey/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WikisWikiKeyArticleKeyEditRoute =
  WikisWikiKeyArticleKeyEditRouteImport.update({
    id: '/wikis/$wikiKey/$articleKey/edit',
    path: '/wikis/$wikiKey/$articleKey/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const GameTestGameKeySceneKeyRoute = GameTestGameKeySceneKeyRouteImport.update({
  id: '/game/test/$gameKey/$sceneKey',
  path: '/game/test/$gameKey/$sceneKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builder/$storyKey': typeof BuilderStoryKeyRoute
  '/builder/stories': typeof BuilderStoriesRoute
  '/library/$storyKey': typeof LibraryStoryKeyRoute
  '/library': typeof LibraryIndexRoute
  '/wikis': typeof WikisIndexRoute
  '/game/$gameKey/$sceneKey': typeof GameGameKeySceneKeyRoute
  '/wikis/$wikiKey/new': typeof WikisWikiKeyNewRoute
  '/wikis/$wikiKey': typeof WikisWikiKeyIndexRoute
  '/game/test/$gameKey/$sceneKey': typeof GameTestGameKeySceneKeyRoute
  '/wikis/$wikiKey/$articleKey/edit': typeof WikisWikiKeyArticleKeyEditRoute
  '/wikis/$wikiKey/$articleKey': typeof WikisWikiKeyArticleKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builder/$storyKey': typeof BuilderStoryKeyRoute
  '/builder/stories': typeof BuilderStoriesRoute
  '/library/$storyKey': typeof LibraryStoryKeyRoute
  '/library': typeof LibraryIndexRoute
  '/wikis': typeof WikisIndexRoute
  '/game/$gameKey/$sceneKey': typeof GameGameKeySceneKeyRoute
  '/wikis/$wikiKey/new': typeof WikisWikiKeyNewRoute
  '/wikis/$wikiKey': typeof WikisWikiKeyIndexRoute
  '/game/test/$gameKey/$sceneKey': typeof GameTestGameKeySceneKeyRoute
  '/wikis/$wikiKey/$articleKey/edit': typeof WikisWikiKeyArticleKeyEditRoute
  '/wikis/$wikiKey/$articleKey': typeof WikisWikiKeyArticleKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builder/$storyKey': typeof BuilderStoryKeyRoute
  '/builder/stories': typeof BuilderStoriesRoute
  '/library/$storyKey': typeof LibraryStoryKeyRoute
  '/library/': typeof LibraryIndexRoute
  '/wikis/': typeof WikisIndexRoute
  '/game/$gameKey/$sceneKey': typeof GameGameKeySceneKeyRoute
  '/wikis/$wikiKey/new': typeof WikisWikiKeyNewRoute
  '/wikis/$wikiKey/': typeof WikisWikiKeyIndexRoute
  '/game/test/$gameKey/$sceneKey': typeof GameTestGameKeySceneKeyRoute
  '/wikis/$wikiKey/$articleKey/edit': typeof WikisWikiKeyArticleKeyEditRoute
  '/wikis/$wikiKey/$articleKey/': typeof WikisWikiKeyArticleKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/builder/$storyKey'
    | '/builder/stories'
    | '/library/$storyKey'
    | '/library'
    | '/wikis'
    | '/game/$gameKey/$sceneKey'
    | '/wikis/$wikiKey/new'
    | '/wikis/$wikiKey'
    | '/game/test/$gameKey/$sceneKey'
    | '/wikis/$wikiKey/$articleKey/edit'
    | '/wikis/$wikiKey/$articleKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/builder/$storyKey'
    | '/builder/stories'
    | '/library/$storyKey'
    | '/library'
    | '/wikis'
    | '/game/$gameKey/$sceneKey'
    | '/wikis/$wikiKey/new'
    | '/wikis/$wikiKey'
    | '/game/test/$gameKey/$sceneKey'
    | '/wikis/$wikiKey/$articleKey/edit'
    | '/wikis/$wikiKey/$articleKey'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/builder/$storyKey'
    | '/builder/stories'
    | '/library/$storyKey'
    | '/library/'
    | '/wikis/'
    | '/game/$gameKey/$sceneKey'
    | '/wikis/$wikiKey/new'
    | '/wikis/$wikiKey/'
    | '/game/test/$gameKey/$sceneKey'
    | '/wikis/$wikiKey/$articleKey/edit'
    | '/wikis/$wikiKey/$articleKey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuilderStoryKeyRoute: typeof BuilderStoryKeyRoute
  BuilderStoriesRoute: typeof BuilderStoriesRoute
  LibraryStoryKeyRoute: typeof LibraryStoryKeyRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  WikisIndexRoute: typeof WikisIndexRoute
  GameGameKeySceneKeyRoute: typeof GameGameKeySceneKeyRoute
  WikisWikiKeyNewRoute: typeof WikisWikiKeyNewRoute
  WikisWikiKeyIndexRoute: typeof WikisWikiKeyIndexRoute
  GameTestGameKeySceneKeyRoute: typeof GameTestGameKeySceneKeyRoute
  WikisWikiKeyArticleKeyEditRoute: typeof WikisWikiKeyArticleKeyEditRoute
  WikisWikiKeyArticleKeyIndexRoute: typeof WikisWikiKeyArticleKeyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wikis/': {
      id: '/wikis/'
      path: '/wikis'
      fullPath: '/wikis'
      preLoaderRoute: typeof WikisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$storyKey': {
      id: '/library/$storyKey'
      path: '/library/$storyKey'
      fullPath: '/library/$storyKey'
      preLoaderRoute: typeof LibraryStoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/stories': {
      id: '/builder/stories'
      path: '/builder/stories'
      fullPath: '/builder/stories'
      preLoaderRoute: typeof BuilderStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$storyKey': {
      id: '/builder/$storyKey'
      path: '/builder/$storyKey'
      fullPath: '/builder/$storyKey'
      preLoaderRoute: typeof BuilderStoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wikis/$wikiKey/': {
      id: '/wikis/$wikiKey/'
      path: '/wikis/$wikiKey'
      fullPath: '/wikis/$wikiKey'
      preLoaderRoute: typeof WikisWikiKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wikis/$wikiKey/new': {
      id: '/wikis/$wikiKey/new'
      path: '/wikis/$wikiKey/new'
      fullPath: '/wikis/$wikiKey/new'
      preLoaderRoute: typeof WikisWikiKeyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameKey/$sceneKey': {
      id: '/game/$gameKey/$sceneKey'
      path: '/game/$gameKey/$sceneKey'
      fullPath: '/game/$gameKey/$sceneKey'
      preLoaderRoute: typeof GameGameKeySceneKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wikis/$wikiKey/$articleKey/': {
      id: '/wikis/$wikiKey/$articleKey/'
      path: '/wikis/$wikiKey/$articleKey'
      fullPath: '/wikis/$wikiKey/$articleKey'
      preLoaderRoute: typeof WikisWikiKeyArticleKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wikis/$wikiKey/$articleKey/edit': {
      id: '/wikis/$wikiKey/$articleKey/edit'
      path: '/wikis/$wikiKey/$articleKey/edit'
      fullPath: '/wikis/$wikiKey/$articleKey/edit'
      preLoaderRoute: typeof WikisWikiKeyArticleKeyEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/test/$gameKey/$sceneKey': {
      id: '/game/test/$gameKey/$sceneKey'
      path: '/game/test/$gameKey/$sceneKey'
      fullPath: '/game/test/$gameKey/$sceneKey'
      preLoaderRoute: typeof GameTestGameKeySceneKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuilderStoryKeyRoute: BuilderStoryKeyRoute,
  BuilderStoriesRoute: BuilderStoriesRoute,
  LibraryStoryKeyRoute: LibraryStoryKeyRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  WikisIndexRoute: WikisIndexRoute,
  GameGameKeySceneKeyRoute: GameGameKeySceneKeyRoute,
  WikisWikiKeyNewRoute: WikisWikiKeyNewRoute,
  WikisWikiKeyIndexRoute: WikisWikiKeyIndexRoute,
  GameTestGameKeySceneKeyRoute: GameTestGameKeySceneKeyRoute,
  WikisWikiKeyArticleKeyEditRoute: WikisWikiKeyArticleKeyEditRoute,
  WikisWikiKeyArticleKeyIndexRoute: WikisWikiKeyArticleKeyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
