/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WhiteboardImport } from './routes/whiteboard'
import { Route as StoreImport } from './routes/store'
import { Route as IndexImport } from './routes/index'
import { Route as LibraryIndexImport } from './routes/library/index'
import { Route as LibraryStoryIdImport } from './routes/library/$storyId'
import { Route as BuilderStoriesImport } from './routes/builder/stories'
import { Route as BuilderStoryIdImport } from './routes/builder/$storyId'
import { Route as GameGameIdIndexImport } from './routes/game/$gameId/index'
import { Route as GameGameIdSceneIdImport } from './routes/game/$gameId/$sceneId'

// Create/Update Routes

const WhiteboardRoute = WhiteboardImport.update({
  path: '/whiteboard',
  getParentRoute: () => rootRoute,
} as any)

const StoreRoute = StoreImport.update({
  path: '/store',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LibraryIndexRoute = LibraryIndexImport.update({
  path: '/library/',
  getParentRoute: () => rootRoute,
} as any)

const LibraryStoryIdRoute = LibraryStoryIdImport.update({
  path: '/library/$storyId',
  getParentRoute: () => rootRoute,
} as any)

const BuilderStoriesRoute = BuilderStoriesImport.update({
  path: '/builder/stories',
  getParentRoute: () => rootRoute,
} as any)

const BuilderStoryIdRoute = BuilderStoryIdImport.update({
  path: '/builder/$storyId',
  getParentRoute: () => rootRoute,
} as any)

const GameGameIdIndexRoute = GameGameIdIndexImport.update({
  path: '/game/$gameId/',
  getParentRoute: () => rootRoute,
} as any)

const GameGameIdSceneIdRoute = GameGameIdSceneIdImport.update({
  path: '/game/$gameId/$sceneId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardImport
      parentRoute: typeof rootRoute
    }
    '/builder/$storyId': {
      id: '/builder/$storyId'
      path: '/builder/$storyId'
      fullPath: '/builder/$storyId'
      preLoaderRoute: typeof BuilderStoryIdImport
      parentRoute: typeof rootRoute
    }
    '/builder/stories': {
      id: '/builder/stories'
      path: '/builder/stories'
      fullPath: '/builder/stories'
      preLoaderRoute: typeof BuilderStoriesImport
      parentRoute: typeof rootRoute
    }
    '/library/$storyId': {
      id: '/library/$storyId'
      path: '/library/$storyId'
      fullPath: '/library/$storyId'
      preLoaderRoute: typeof LibraryStoryIdImport
      parentRoute: typeof rootRoute
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId/$sceneId': {
      id: '/game/$gameId/$sceneId'
      path: '/game/$gameId/$sceneId'
      fullPath: '/game/$gameId/$sceneId'
      preLoaderRoute: typeof GameGameIdSceneIdImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId/': {
      id: '/game/$gameId/'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  StoreRoute,
  WhiteboardRoute,
  BuilderStoryIdRoute,
  BuilderStoriesRoute,
  LibraryStoryIdRoute,
  LibraryIndexRoute,
  GameGameIdSceneIdRoute,
  GameGameIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/store",
        "/whiteboard",
        "/builder/$storyId",
        "/builder/stories",
        "/library/$storyId",
        "/library/",
        "/game/$gameId/$sceneId",
        "/game/$gameId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/store": {
      "filePath": "store.tsx"
    },
    "/whiteboard": {
      "filePath": "whiteboard.tsx"
    },
    "/builder/$storyId": {
      "filePath": "builder/$storyId.tsx"
    },
    "/builder/stories": {
      "filePath": "builder/stories.tsx"
    },
    "/library/$storyId": {
      "filePath": "library/$storyId.tsx"
    },
    "/library/": {
      "filePath": "library/index.tsx"
    },
    "/game/$gameId/$sceneId": {
      "filePath": "game/$gameId/$sceneId.tsx"
    },
    "/game/$gameId/": {
      "filePath": "game/$gameId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
