services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - net

  story-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
    environment:
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
      - PORT=$PORT
    networks:
      - net

  story-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    environment:
      - NODE_ENV=production
    networks:
      - net

volumes:
  mongo-data:
    driver: local

networks:
  net:
