### create user
POST http://localhost:8000/api/user/register HTTP/1.1
content-type: application/json

{
  "email": "string@string.strin",
  "username": "stri",
  "password": "string"
}

### get user
POST http://localhost:8000/api/user/login HTTP/1.1
content-type: application/json

{
  "usernameOrEmail": "stri",
  "password": "string"
} 

### get storie
GET http://localhost:8000/api/store/load HTTP/1.1